import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import Login from './Login';
import SignUp from './SignUp';
import Queue from './Queue';
import registerServiceWorker from './registerServiceWorker';
import 'semantic-ui-css/semantic.min.css';
import lg from  './lg.jpeg';
import Main from './Main';
console.log(sessionStorage.token);
window.controlSocket = new WebSocket('ws://127.0.0.1:8000/ws/control/');
ReactDOM.render(<Main/>, document.getElementById('root'));
registerServiceWorker();
